using LINQ in the code
Rychu-Pawel/PeselValidator pull request #10
Opened 2019-09-09 09:39 UTC by Jankowski-J

Masz tu @Rychu-Pawel trochę LINQ.

2019-11-04 18:49 UTC, Rychu-Pawel commented on src/PeselValidator/PeselValidator.cs
> +            var sum = weights.Select((x, i) => x * int.Parse(pesel[i].ToString())).Sum();
Thanks @Jankowski-J for this PR. I checked the performance of this code and unfortunatly it is 3 times slower than the original one. 
I like the change with `Last()` though. It clrealy highlights the intent.
I did some more testing and looks like we can get the lost performance back by using `Convert.ToInt32` in line 53 and `Convert.ToChar` in line 48. Then these three `.ToString()`s are redundant and can be removed.
Could you please implement these changes?

2019-11-04 18:50 UTC, Rychu-Pawel requested changes
Thanks @Jankowski-J for this PR. I checked the performance of this code and unfortunatly it is 3 times slower than the original one.
I like the change with `Last()` though. It clrealy highlights the intent.
I did some more testing and looks like we can get the lost performance back by using `Convert.ToInt32` in line 53 and `Convert.ToChar` in line 48. Then these three `.ToString()`s are redundant and can be removed.
Could you please implement these changes?

2019-11-04 18:55 UTC, Rychu-Pawel commented
Would it be also possible to rebase your branch on the latest develop? It should fix appveyor build crashing on sonarqube analysis. Thanks in advance.

2019-11-11 10:09 UTC, Jankowski-J commented
Suggested fixes - using `Convert` methods - fail the tests.
Using `Convert` would still require using `.ToString()` to produce valid output.
Since you are concerned about the performance, should this PR be abandoned?

2019-11-12 19:51 UTC, Rychu-Pawel commented
@Jankowski-J 
The biggest performance killer is the change in `CalculateChecksum`. Here I would stick to the standard `for` loop. The change with `.Last()`, on the other hand, looks fine for me. I would like to merge this one.
And, yea, of course `Convert` breaks the tests. My bad. Sorry. Could you please use `char.GetNumericValue` instead? This one works for sure and is faster than comparing `.ToString()`s :)

2019-11-12 20:42 UTC, Jankowski-J commented
Changed as per suggestions.

2019-11-13 20:24 UTC, Rychu-Pawel approved these changes

2019-11-13 20:25 UTC, merged

2019-11-13 21:16 UTC, Jankowski-J commented
:partyparrot:

Pozdrawiam,
Jakub Jankowski

________________________________
From: Rychu <notifications@github.com>
Sent: Wednesday, November 13, 2019 9:25:04 PM
To: Rychu-Pawel/PeselValidator <PeselValidator@noreply.github.com>
Cc: JJankowski <jankowski.jakub@outlook.com>; Mention <mention@noreply.github.com>
Subject: Re: [Rychu-Pawel/PeselValidator] using LINQ in the code (#10)


Merged #10<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRychu-Pawel%2FPeselValidator%2Fpull%2F10&data=02%7C01%7C%7Ccfd10830b54446f3f04208d7687791ee%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637092735059708262&sdata=WiWYFTqjiW5PRDPm%2FF%2FPIJVwYRGIXJusY92my2Rpgis%3D&reserved=0> into develop.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRychu-Pawel%2FPeselValidator%2Fpull%2F10%3Femail_source%3Dnotifications%26email_token%3DAAQLRFAJ7O4MP3PEEXPAWFTQTRPCBA5CNFSM4IUY6DCKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOU2ZE5DA%23event-2796703372&data=02%7C01%7C%7Ccfd10830b54446f3f04208d7687791ee%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637092735059728272&sdata=Y18u762m%2BjYifDqINR9grOCM2%2FEVXM7ESwnkP61gvYc%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAQLRFH4WK5YPUKBB6Q5H7TQTRPCBANCNFSM4IUY6DCA&data=02%7C01%7C%7Ccfd10830b54446f3f04208d7687791ee%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637092735059738284&sdata=fflQG5GlAkRzNWRS6M1rdBi0CthqyY1LzVT1cMeWZEo%3D&reserved=0>.